# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_author',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_keywords',
        ),
        migrations.AddField(
            model_name='article',
            name='article_keywords',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
